HospitalManage/HospitalManage/Models/solitaire.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Models
{
  public   class solitaire
    {
     public int Id { get; set; }
        /// <summary>
        /// 接龙班次ID
        /// </summary>
     public int SolitaireClassID { get; set; }
        /// <summary>
        /// 接龙开始时间
        /// </summary>
     public DateTime StartSolitaire { get; set; }
        /// <summary>
        /// 接龙结束时间
        /// </summary>
     public DateTime LastStartSolitaire { get; set; }
        /// <summary>
        /// 接龙组序
        /// </summary>
     public int SolitaireSort { get; set; }
        /// <summary>
        /// 组内人员
        /// </summary>
     public string GropCrew { get; set; }
        /// <summary>
        /// 组长
        /// </summary>
     public string GroupLeader { get; set; }

    }
}

HospitalManage/HospitalManage/Controllers/SolitaireController.cs
using CommHelps;
using IServices;
using Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;

namespace HospitalManage.Controllers
{
    using Services;
    using IServices;
    using Models;
    public class SolitaireController : Controller
    {
        [Unity.Attributes.Dependency]
        public IClassesService ClassesServices { get; set; }
        [Unity.Attributes.Dependency]
        public ISolitaireService solitaireService { get; set; }
        [Unity.Attributes.Dependency]
        public IChainsGroupService chainsGroupService { get; set; }
        [Unity.Attributes.Dependency]
        public IUsersServices usersServices { get; set; }
        static int index = 0;
        // GET: Solitaire
        public ActionResult Index()
        {
            //List<string []> w =new List<string[]> { new string[] { "1", "lkjlj", "khll", "ghg" }, new string[] { "jkh", "lkjlj", "khll", "ugjjhjg" }, new string[] { "jkh", "lkjlj", "khll", "ugjjg" } };
        
            //ViewBag.y = w;
            return View();
        }
        /// <summary>
        /// 接龙显示
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult IndexShow()
        {
            using (MySqlConnection conn = DapperHelper.Instance().GetConnection())
            {
                List<SoChains> list = conn.Query<SoChains>("up_ChainsTable", null).ToList();
                return Json(list, JsonRequestBehavior.AllowGet);
            }
        }
        /// <summary>
        /// 班次
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult ClassesList()
        {
            ///获得所有班次信息
            var clasees = ClassesServices.GetClasses();
            return Json(clasees.ToList(), JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 接龙小组
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult ChainsGroupList()
        {
            
            var clasees = chainsGroupService.SelectChainsGroup();
            return Json(clasees.ToList(), JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 获取用户列表
        /// </summary>
        /// <returns></returns>

        public List<Users> UsersList()
        {

            //var users =   Json(usersServices.ShowUsers(), JsonRequestBehavior.AllowGet);
            //return users;
            var users = usersServices.ShowUsers().ToList();
            return users;
        }
        public ActionResult AddChains()
        {
            //ViewBag.ids = 0;
            //string  ids= Request.QueryString["ids"];//获取传过来的值
            //if (ids!=null)
            //{
            //    ViewBag.ids = ids;
            //}
            
            return View();
        }
        /// <summary>
        /// 添加接龙组
        /// </summary>
        /// <param name="solitaire"></param>
        /// <param name="chainsGroups"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult AddChains(Solitaire solitaire, ChainsGroup[] chainsGroups)
        {
            var ids = "";
            Solitaire solitaireIf = solitaireService.SelectSolitaire().Where(m => m.SolitaireClassID == solitaire.SolitaireClassID).FirstOrDefault();
            if (solitaireIf != null)
            {
                return Json("");
            }
            List<ChainsGroup> groupListToAdd = new List<ChainsGroup>();
            foreach (var item in chainsGroups)
            {
                if (item.GropCrew!=null)
                {
                    groupListToAdd.Add(item);
                }
            }

            int j = chainsGroupService.AddChainsGroup(groupListToAdd);
            List<ChainsGroup> chainsGroupList= chainsGroupService.SelectChainsGroup().Where(m => m.ClassesId == solitaire.SolitaireClassID).ToList();
            foreach (var item in chainsGroupList)
            {
                ids += item.Id+",";
            }
            solitaire.ChainsGroupIds = ids.Substring(0,ids.Length-1);
            Solitaire solitaireModel = solitaireService.SelectSolitaire().LastOrDefault();
            if (solitaireModel!=null)
            {
                solitaire.SoSortNumber = solitaireModel.SoSortNumber + 1;
            }
            else
            {
                solitaire.SoSortNumber = 1;
            }
            int i = solitaireService.AddSolitaire(solitaire);
            using (MySqlConnection conn = DapperHelper.Instance().GetConnection())
            {
                List<SoChains> list = conn.Query<SoChains>("up_ChainsTable", null).ToList();
                return Json(list);
            }
            
        }
        static List<SoChains> list = new List<SoChains>();
        public ActionResult UodateChains(string classesName)
        {
            //string chainsClasses = Request.QueryString["classesName"].Trim();
            using (MySqlConnection conn = DapperHelper.Instance().GetConnection())
            {
                list = conn.Query<SoChains>("up_ChainsTable", null).Where(m=>m.ClassesName== classesName).ToList();
                //ViewBag.list = Json(list);
                return View();
            }
        }
        /// <summary>
        /// 修改反填
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult getUodateChains()
        {
            return Json(list,JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 修改接龙
        /// </summary>
        /// <param name="solitaire"></param>
        /// <param name="chainsGroups"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult UodateChains(Solitaire solitaire, ChainsGroup[] chainsGroups)
        {
            var ids = "";
            List<ChainsGroup> chainsGroupsToAdd = new List<ChainsGroup>();
            List<ChainsGroup> chainsGroupsToUpdate = new List<ChainsGroup>();
            List<ChainsGroup> chainsGroupsToDel = new List<ChainsGroup>();
            foreach (var item in chainsGroups)
            {
                if (item.Id==0)
                {
                    if (item.GropCrew!=null)
                    {
                        chainsGroupsToAdd.Add(item);
                    }                             
                }
                else
                {
                    if (item.GropCrew !=null)
                    {
                        chainsGroupsToUpdate.Add(item);
                    }
                    else
                    {
                        chainsGroupsToDel.Add(item);
                    }
                }
            }
           
            int i = 0;
            if (chainsGroupsToUpdate.Count != 0)
            {
                
                for (i = 0; i < chainsGroupsToUpdate.Count; i++)
                {
                    chainsGroupsToUpdate[i].SortNumber = i + 1;
                }
                int updateResult = chainsGroupService.UpdateChainsGroup(chainsGroupsToUpdate);
            }
            if (chainsGroupsToDel.Count != 0)
            {
                int updateResult = chainsGroupService.DelChainsGroup(chainsGroupsToDel);
            }
            int j = 0;
            if (chainsGroupsToAdd.Count != 0)
            {
                ChainsGroup  chainsGroup = chainsGroupService.SelectChainsGroup().Where(m => m.ClassesId == solitaire.SolitaireClassID).LastOrDefault();
                for (j = 0; j < chainsGroupsToAdd.Count; j++)
                {
                    chainsGroupsToAdd[j].SortNumber = chainsGroup.SortNumber + j+1;
                }
                int addResult = chainsGroupService.AddChainsGroup(chainsGroupsToAdd);
            }
            List<ChainsGroup> chainsGroupList = chainsGroupService.SelectChainsGroup().Where(m => m.ClassesId == solitaire.SolitaireClassID).ToList();
            foreach (var item in chainsGroupList)
            {
                ids += item.Id + ",";
            }
            solitaire.ChainsGroupIds = ids.Substring(0, ids.Length - 1);
            int result = solitaireService.UpdateSolitaire(solitaire);
            using (MySqlConnection conn = DapperHelper.Instance().GetConnection())
            {
                List<SoChains> list = conn.Query<SoChains>("up_ChainsTable", null).ToList();
                return Json(list);
            }
        }
        /// <summary>
        /// 添加组员
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult AddMember(int id)
        {
            index = id;
            ViewBag.index = index;
            return View(UsersList());
        }
        [HttpPost]
        public void DelChains(int classesId)
        {
        
            int i = 0;
            int delSoResult = solitaireService.DelSolitaire(classesId);
            List<ChainsGroup> chainsGroupsToDel = chainsGroupService.SelectChainsGroup().Where(m => m.ClassesId == classesId).ToList();
       
            int delChResult = chainsGroupService.DelChainsGroup(chainsGroupsToDel);
            List<Solitaire> list = solitaireService.SelectSolitaire().ToList();
            for (i = 0; i < list.Count; i++)
            {
                list[i].SoSortNumber = i + 1;
                int updateResult = solitaireService.UpdateSolitaire(list[i]);
            }
           
        }
    }
}

HospitalManage/HospitalManage/Views/Solitaire/AddChains.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>接龙设置</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <link rel="stylesheet" href="~/css/x-admin.css" media="all">
    <link rel="stylesheet" href="~/css/pag.css" media="all">

    <script src="~/Scripts/vue.js"></script>
    <script src="~/Scripts/axios.js"></script>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/js/My97DatePicker/My97DatePicker/WdatePicker.js"></script>
</head>

<body>
    <div id="app" class="x-body">
        <div style="margin:0 auto">
            <div>
                <span style="float:left;margin-right:20px">接龙班次</span>
                <select v-model="id" lay-verify="required" name="cid" class="layui-input" style="width:96px;float:left">
                    <option v-for="classes in classesList" v-bind:value="classes.Id">{{classes.ClassesName}}</option>
                    @*//v-bind:value="classes.id" v-on:input="id=$event.target.value"*@
                </select>
            </div>
            <div style="margin-left:500px">
                <span style="float:left;margin-right:20px">接龙周期</span>
                <div style="float:left">
                    @*<div><span style="background-color:darkviolet">开始时间</span><input id="Text1" type="text" onclick="WdatePicker()" v-on:change="getstartTime()" v-model="startTime" /></div>
        <div><span style="background-color:aquamarine">结束时间</span><input id="Text1" type="text" onclick="WdatePicker()" v-on:change="getendTime()" v-model="endTime" /></div>*@
                    <div><span style="background-color:darkviolet">开始时间</span><input id="startTime" type="text" onclick="WdatePicker()" /></div>
                    <div><span style="background-color:aquamarine">结束时间</span><input id="endTime" type="text" onclick="WdatePicker()" /></div>

                </div>
            </div>
        </div>
        <div style="margin-top:150px">
            <table class="tablelist" border="1">
                <thead>
                    <tr>  <th colspan="4" style="text-align:center">组员设置</th></tr>
                    <tr>

                        <th>组序</th>
                        <th> 人员 </th>
                        <th> 组长</th>
                        <th> </th>

                    </tr>
                </thead>
                <tbody id="tbl">
                    <tr :id="chainsGroup.SortNumber" class="groupInfo" v-for="(chainsGroup,index) in chainsGroupList">
                        <td>{{index+1}}</td>
                        <td v-if="chainsGroup.GropCrew!=''" v-on:click="user_management_edit('人员设置', '/Solitaire/AddMember?id='+chainsGroup.SortNumber, '800', '500')">
                            {{chainsGroup.GropCrew}}
                        </td>
                        <td v-else v-on:click="user_management_edit('人员设置', '/Solitaire/AddMember?id='+chainsGroup.SortNumber, '800', '500')">
                            <img src="~/images/t06.png" />
                        </td>
                        <td v-if="chainsGroup.GropCrew!=''">

                            <select  lay-verify="required" name="cid" class="layui-input" >
                                <option v-for="gropCrewx in chainsGroup.GropCrew.split(',')" v-bind:value="gropCrewx">{{gropCrewx}}</option>
                            </select>
                        </td>
                        <td v-else ><input id="Hidden1" type="hidden" v-model="chainsGroup.GroupLeader" value="chainsGroup.GroupLeader"/></td>
                        <td v-on:click="addRow(id)"><img src="~/images/t01.png" /></td>
                    </tr>

                </tbody>
            </table>
        </div>
        <div style="width:200px;margin:50px auto">
            <button class="layui-btn" v-on:click="addChains()"> 保存 </button>
            <button class="layui-btn" style="float:right" onclick="cancel()"> 取消 </button>

        </div>
    </div>
    <script src="~/lib/layui/layui.js" charset="utf-8">
    </script>
    <script src="~/js/x-layui.js" charset="utf-8">
    </script>
    <script>
        layui.use(['form', 'layer'], function () {
            $ = layui.jquery;
            var form = layui.form()
                , layer = layui.layer;
        });
        //function user_management_edit(title, url, w, h) {
        //    x_admin_show(title, url, w, h);
        //}
        function setChooseValues(ref, indexId) {

           localStorage.ids = ref;
           //alert(localStorage.ids);
            //alert(indexId);
            //$("#" + indexId).children("td").eq(1).children().eq(0).val(localStorage.ids);
            //$("#" + indexId).children("td").eq(1).text(localStorage.ids);
            vm.ChooseValues(indexId);
        }

        function cancel() {
            var index = parent.layer.getFrameIndex(window.name);
            parent.layer.close(index); 
        }
    </script>


    <script type="text/javascript">
       
        var vm = new Vue({
            el: "#app",
            data: {
               
                sortNumber:1,
                classesList: [],             
                chainsGroupList: [{ Id: "", GroupLeader: "", GropCrew: "", ClassesId: 0, SortNumber: 1 }],
                //gropCrewList: [],
                groupList: [],
                SortNumber: 1,         
                GropCrew: "",
                GroupLeader: "",
                id: 1,
          
            },
            //computed: {//计算属性_——计算属性一定要return一个值，这个值存在属性里。计算属性和data属性可以简单的理解为数据的不同形式。
            //    gropCrewList: function () {
            //        return this.GropCrew.split(',')
            //    }
            //},
            mounted() {
                this.load();
                
                this.getClassesList();
            },
            methods: {
         
                user_management_edit(title, url, w, h) {
                    console.log(url);
                    x_admin_show(title, url, w, h);
                },
                load: function () {
                    localStorage.ids = "";
                    this.GropCrew = "";
                    //alert(localStorage.ids);
                    //alert(this.GropCrew);
                },
                ChooseValues: function (rowNumber) {
                 
                    if (localStorage.ids != null) {
                        this.GropCrew = localStorage.ids;
                        var groupIndex = rowNumber-1;
                        this.chainsGroupList[groupIndex].GropCrew = localStorage.ids;
                        
                    }
               
                },
                addRow: function (classesId) {
                    this.sortNumber += 1;
                    this.chainsGroupList.push({ Id: "", GroupLeader: "", GropCrew: "", ClassesId: classesId, SortNumber: this.sortNumber });
                },
                getClassesList: function () {
                     axios.get('@Url.Action("ClassesList", "Solitaire")'
                    ).then(
                        (response) => {
                            this.classesList = [];
                            for (var i = 0; i < response.data.length; i++) {
                                this.classesList.push(response.data[i]);
                            }

                        },
                        (response) => {
                            alert(response.status);
                        }
                    ).catch(function (response) {
                        alert(response);
                    });
                },

                addChains: function () {
                    var _this = this;
                    _this.groupList = [];
                    $(".groupInfo").each(function () {//注意不能id选择器，因为只会选中一个
                       
                        _this.groupList.push({ SortNumber: this.cells[0].innerText, ClassesId: _this.id, GropCrew: this.cells[1].innerText, GroupLeader: this.cells[2].firstElementChild.value });
                
                    });
                    var startTime = $("#startTime").val();
                    var endTime = $("#endTime").val();
                   
                    axios.post('@Url.Action("AddChains", "Solitaire")', {
                        solitaire: { SolitaireClassID: _this.id, StartSolitaire: startTime, LastStartSolitaire: endTime },
                        chainsGroups: this.groupList
                    }).then(
                        (response) => {
                            parent.setChainsList(response.data)
                        }
                    ).catch(function (response) {
                        alert(response);
                        });
                 
                    var index = parent.layer.getFrameIndex(window.name);
                    parent.layer.close(index); 
                },

               
                
                deleteSolitaireById: function (id) {
                    axios.post('@Url.Action("DelSolitaire", "Solitaire")', { id: id }).then(
                        (response) => {
                            this.SolitaireList = [];
                            for (var i = 0; i < response.data.length; i++) {
                                this.SolitaireList.push(response.data[i]);
                            }
                            this.SolitaireList.push({ Id: "", SolitaireName: "" });
                        },
                        (response) => {
                            alert(response.status);
                        }
                    ).catch(function (response) {
                        alert(response);
                    });
                }
            }
        })
    </script>
</body>
</html>

HospitalManage/HospitalManage/Views/Solitaire/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>接龙设置</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <link rel="stylesheet" href="~/css/x-admin.css" media="all">
    <link rel="stylesheet" href="~/css/pag.css" media="all">
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/vue.js"></script>
    <script src="~/Scripts/axios.js"></script>
</head>
<body>
    <div class="x-nav"> <span class="layui-breadcrumb"> <a><cite>首页</cite></a> <a><cite>接龙设置</cite></a> </span> <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新"><i class="layui-icon" style="line-height:30px">ဂ</i></a> </div>
    <div id="app" class="x-body">


        <div class="tools">
            <div class="layui-input-inline" style="width:200px;float:left">
                <input type="text" name="link" placeholder="班次名称" autocomplete="off" class="layui-input">
            </div>
            <ul class="toolbar" style="float:left">

                <li onclick="user_management_show('用户查看','Dangan-look.html','600','500')"><span><img src="~/images/t06.png" /></span>查询</li>
                <li v-on:click="user_management_del()"><span><img src="~/images/t03.png" /></span>删除</li>
                <li onclick="user_management_add('接龙设置','/Solitaire/AddChains','1000','600')"><span><img src="~/images/t01.png" /></span>添加</li>
                <li v-on:click="user_management_edit('接龙设置','/Solitaire/UodateChains?classesName=','1000','600')"><span><img src="~/images/t02.png" /></span>编辑</li>

            </ul>
            <span class="x-right" style="line-height:25px">共有数据：88 条</span>
        </div>
        <table class="tablelist" border="1">
            <thead>
                <tr>

                    <th>序号</th>
                    <th> 接龙班次 </th>
                    <th> 接龙周期</th>
                    <th> 接龙组序</th>
                    <th> 组内人员</th>
                    <th> 组长 </th>
                    <th> 轮转排序 </th>

                </tr>
            </thead>
            <tbody>

                <tr v-for="(item,index) in chainsList">
                    <td :rowspan="item.ChainsGroupIds.split(',').length" v-if="item.SortNumber==1">{{item.SoSortNumber}}</td>
                    <td :rowspan="item.ChainsGroupIds.split(',').length" v-if="item.SortNumber==1" v-on:click="clickfun" :id="item.SolitaireClassID">
                        {{item.ClassesName}}
                    </td>
                    <td :rowspan="item.ChainsGroupIds.split(',').length" v-if="item.SortNumber==1">
                        <span style="display:block"><span style="display:block;margin-bottom:-10px">开始时间：</span>{{ChangeDateFormat(item.StartSolitaire)}}</span>
                        <span style="display:block"><span style="display:block;margin-bottom:-10px">结束时间：</span>{{ChangeDateFormat(item.LastStartSolitaire)}}</span>
                    </td>
                    <td>
                        <span>{{item.SortNumber}}</span>

                    </td>
                    <td>{{item.GropCrew}}</td>
                    <td>{{item.GroupLeader}}</td>
                    <td></td>
                </tr>




            </tbody>
        </table>
        @*<div class="page">
                <div class="pagelist">
                    <span class="jump">上一页</span> <span class="jump">1</span> <span class="jump">2</span> <span class="jump">3</span> <span class="jump">4</span> <span class="jump">5</span> <span class="jump">6</span> <span class="ellipsis">...</span> <span class="jump">下一页</span> <span class="jumppoint">跳转到：</span> <span class="jumpinp">
                        <input type="text">
                    </span> <span class="jump gobtn">GO</span>
                </div>
            </div>*@
    </div>
    <br />
    <br />
    <br />
    <script src="~/lib/layui/layui.js" charset="utf-8"></script>

    <script src="~/js/addChains-layui.js" charset="utf-8"></script>
    <script src="~/js/jquery2.js" charset="utf-8"></script>
    <script src="~/js/js.js" charset="utf-8"></script>
    <script>
        layui.use(['laydate', 'element', 'laypage', 'layer'], function () {
            $ = layui.jquery;
            lement = layui.element();//面包导航
            laypage = layui.laypage;//分页
            layer = layui.layer;//弹出层

        });
        /*用户-添加*/
        function user_management_add(title, url, w, h) {
            x_admin_show(title, url, w, h);
        }
        /*用户-查看*/
        function user_management_show(title, url, w, h) {
            x_admin_show(title, url, w, h);
        }

        //gong子窗体调用
        function setChainsList(chainsList) {
            vm.getChainsList(chainsList);
        }



    </script>
    <script type="text/javascript">
        $('.tablelist tbody tr:odd').addClass('odd');
    </script>


    <script type="text/javascript">

        var vm = new Vue({
            el: "#app",
            data: {

                chainsList:[],
                chainsClasses: "",
                chainsClassesId:0
            },
            mounted() {
                this.showChainsList();
            },
            methods: {
                clickfun: function (e) {
                    var el = e.target;

                    this.chainsClasses = $(el).text().trim();
                    this.chainsClassesId = $(el).prop("id");
                },
                ChangeDateFormat(cellval) {

                var date = new Date(parseInt(cellval.replace("/Date(", "").replace(")/", ""), 10));

                var month = date.getMonth() + 1 < 10 ? "0" + (date.getMonth() + 1) : date.getMonth() + 1;

                var currentDate = date.getDate() < 10 ? "0" + date.getDate() : date.getDate();

                return date.getFullYear() + "-" + month + "-" + currentDate;

                },
                // 用户-编辑
                user_management_edit: function (title, url, w, h) {

                    x_admin_show(title, url + this.chainsClasses, w, h);
                },
                user_management_del: function () {
                    alert(this.chainsClassesId);
                    alert(this.chainsClasses);
                    axios.post('@Url.Action("DelChains", "Solitaire")', { classesId: this.chainsClassesId }).then(
                        (response) => {
                            this.showChainsList();
                        },
                        (response) => {
                            alert(response.status);
                        }
                    ).catch(function (response) {
                        alert(response);
                    });
                },
                getChainsList: function (chainss) {

                    //this.chainsList = [];
                    //for (var i = 0; i < chainss.length; i++) {
                    //    this.chainsList.push(chainss[i]);
                    //}
                    this.showChainsList();
                },
                showChainsList: function () {
                    axios.get('@Url.Action("IndexShow", "Solitaire")'
                    ).then(
                        (response) => {
                            this.chainsList = [];
                            for (var i = 0; i < response.data.length; i++) {
                                this.chainsList.push(response.data[i]);
                            }
                            //this.chainsList = response.data;
                            //alert(this.chainsList);

                        },
                        (response) => {
                            alert(response.status);
                        }
                    ).catch(function (response) {
                        alert(response);
                    });
                }
            }

        })
    </script>

</body>
</html>