HospitalManage/HospitalManage/Models/Approvalflow.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Services
{
    /// <summary>
    /// 审批流程配置表
    /// </summary>
   public class Approvalflow
    {
        /// <summary>
        /// 主键id
        /// </summary>
       public int Id { get; set; }
        /// <summary>
        /// 审批业务id
        /// </summary>
        public int ApprovalID { get; set; }
        /// <summary>
        /// 配置流程编码
        /// </summary>
        public string FlowCode { get; set; }
        /// <summary>
        /// 审批科室id
        /// </summary>
        public int DepartmentID { get; set; }
        /// <summary>
        /// 判断条件id
        /// </summary>
        public int ConditionID { get; set; }
        /// <summary>
        /// 审批状态
        /// </summary>
        public int ApprovalStatus { get; set; }
        /// <summary>
        /// 审批类型
        /// </summary>
        public string ApprovalType { get; set; }
        /// <summary>
        /// 审批方式
        /// </summary>
        public string ApprovalWay { get; set; }
        /// <summary>
        /// 申请人角色id
        /// </summary>
        public int DutyID { get; set; }
        /// <summary>
        /// 审批起点
        /// </summary>
        public string StartApproval { get; set; }
        /// <summary>
        /// 审批终点
        /// </summary>
        public string LastApproval { get; set; }
        /// <summary>
        /// 审批人ids
        /// </summary>
        public int UserIDs { get; set; }
        











    }
}

HospitalManage/HospitalManage/Controllers/ApprovalflowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalManage.Controllers
{
    using Models;
    using IServices;
    public class ApprovalflowController : Controller
    {
        IApprovalflowServices iapprovalflowServices = null;
        public ApprovalflowController(IApprovalflowServices approvalflowServices)
        {
            iapprovalflowServices = approvalflowServices;
        }
        // GET: Approvalflow
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 添加审批条件
        /// </summary>
        /// <returns></returns>
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public int Add(Approvalflow approvalflow)
        {
            return iapprovalflowServices.Add(approvalflow);
        }
        /// <summary>
        /// 显示审批条件
        /// </summary>
        /// <returns></returns>
        public ActionResult Show()
        {
            return View();
        }
        [HttpGet]
        public JsonResult Shows()
        {
            return Json(iapprovalflowServices.Show(), JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 修改审批条件
        /// </summary>
        /// <returns></returns>
        public ActionResult Update()
        {
            return View();
        }
        [HttpPost]
        public int Update(Approvalflow approvalflow)
        {
            var result = iapprovalflowServices.Update(approvalflow);
            return result;
        }
        /// <summary>
        /// 获取id
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        // GET: Users
        public JsonResult Get(int Id)
        {
            return Json(iapprovalflowServices.Get(Id), JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 删除审批条件
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        [HttpPost]
        public int Delete(int Id)
        {
            return iapprovalflowServices.Delete(Id);
        }
        /// <summary>
        /// 根据科室获取用户
        /// </summary>
        /// <param name="DepartmentID"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetUser(string DepartmentID)
        {
            return Json(iapprovalflowServices.GetUsers(Convert.ToInt32(DepartmentID)), JsonRequestBehavior.AllowGet);
        }
    }
}

HospitalManage/HospitalManage/Views/Approvalflow/Show.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Show</title>
    <script src="~/Scripts/axios.js"></script>
    <script src="~/Scripts/vue.js"></script>
    <link href="~/css/pag.css" rel="stylesheet" media="all" />
    <link href="~/css/css.css" rel="stylesheet" media="all" />
    <link href="~/css/x-admin.css" rel="stylesheet" media="all" />
</head>
<body style="background-color:#ffffff">
    <div id="app" class="x-body">
        <a href="#" onclick="location.href='/Approvalflow/Add'"><span><img src="~/images/t01.png" /></span>添加</a>
        <table class="tablelist">
            <thead>
                <tr>
                    <th>编号</th>
                    <th>业务名称</th>
                    <th>配置流程编码</th>
                    <th>科室名称</th>
                    <th>条件名称</th>
                    <th>审批类型</th>
                    <th>审批方式</th>
                    <th>申请人职务</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody id="x-link">
                <tr v-for="(item,key,index) in List">
                    <td>{{item.Id}}</td>
                    <td>{{item.ApprovalName}}</td>
                    <td>{{item.FlowCode}}</td>
                    <td>{{item.DepartmentName}}</td>
                    <td>{{item.Conditions}}</td>
                    <td>{{item.ApprovalType}}</td>
                    <td>{{item.ApprovalWay}}</td>
                    <td>{{item.DutyName}}</td>
                    <td>
                        <div v-if="item.Id!=''">
                            <a href="#" v-on:click="GetRules(item.Id)">修改</a>
                            <a href="javascript:void(0)" v-on:click="DeleteRule(item.Id)">删除</a>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <script src="~/js/x-layui.js" charset="utf-8"></script>
    <script src="~/lib/layui/layui.js" charset="utf-8"></script>
    <script src="~/js/jquery2.js" charset="utf-8"></script>
    <script src="~/js/js.js" charset="utf-8"></script>
    <script>
        layui.use(['element', 'laypage', 'layer', 'form'], function () {
            $ = layui.jquery;//jquery
            lement = layui.element();//面包导航
            laypage = layui.laypage;//分页
            layer = layui.layer;//弹出层
            form = layui.form();//弹出层
        });
        // 编辑
        function data_management_look(title, url, id, w, h) {
            x_admin_show(title, url, w, h);
        }

    </script>
    <script type="text/javascript">
        $('.tablelist tbody tr:odd').addClass('odd');
    </script>
    <script>
        var vm = new Vue({
            el: "#app",
            data: {
               Id:"",
               List: [],
            },
            mounted() {
                this.Show();
            },
            methods: {
                Show: function () {
                    axios.get('@Url.Action("Shows", "Approvalflow")').then(
                        (response) => {
                            console.log(response)
                            this.List = response.data;
                        },
                        (response) => {
                            alert(response.status);
                        }
                    ).catch(function (response) {
                        alert(response);
                    });
                },
                GetRules: function (Id) {
                    location.href = "Update?Id=" + Id;
                },
                DeleteRule: function (Id) {
                        axios.post('@Url.Action("Delete", "Approvalflow")', { Id: Id }).then(
                        (response) => {
                            if (response.data > 0) {
                                alert("删除成功")
                                this.Show();
                            }
                        },
                        (response) => {
                            alert(response.status);
                        }
                    ).catch(function (response) {
                        alert(response);
                    });
                },

            }
        })
    </script>
</body>
</html>