HospitalManage/HospitalManage/Models/Arrangeoperation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Services
{
    /// <summary>
    /// 手术申请表
    /// </summary>
   public class Arrangeoperation
    {
        /// <summary>
        /// 主键id
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// 手术间id
        /// </summary>
        public int OperationID { get; set; }
        /// <summary>
        /// 科室id
        /// </summary>
        public int DepartmentID { get; set; }
        /// <summary>
        /// 手术名称
        /// </summary>
        public string OperationName { get; set; }
        /// <summary>
        /// 主刀医生
        /// </summary>
        public string OperatorDoctor { get; set; }
        /// <summary>
        /// 器械
        /// </summary>
        public string Instrument { get; set; }
        /// <summary>
        /// 巡回
        /// </summary>
        public string Tour { get; set; }
        /// <summary>
        /// 麻醉师
        /// </summary>
        public string Anesthetist { get; set; }
        /// <summary>
        /// 患者姓名
        /// </summary>
        public string PatientName { get; set; }
        /// <summary>
        /// 年龄
        /// </summary>
        public string PatientAge { get; set; }
        /// <summary>
        /// 性别
        /// </summary>
        public string PatientSex { get; set; }

    }
}

HospitalManage/HospitalManage/Controllers/ArrangeoperationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalManage.Controllers
{
    using Services;
    using IServices;
    using Models;
    public class ArrangeoperationController : Controller
    {
        IArrangeoperationServices iarrangeoperationServices = null;
        IDepartmentServices idepartmentServices = null;
        IOperationServices ioperation = null;
        public ArrangeoperationController(IArrangeoperationServices arrangeoperationServices, IDepartmentServices departmentServices, IOperationServices operation)
        {
            idepartmentServices = departmentServices;
            iarrangeoperationServices = arrangeoperationServices;
            ioperation = operation;
        }
        /// <summary>
        /// 显示手术申请
        /// </summary>
        /// <returns></returns>
        // GET: Arrangeoperation
        public ActionResult Index()
        {
            return View();
        }

        //[HttpGet]
        //public JsonResult Indexs()
        //{
        //    return Json(iarrangeoperationServices.Show(), JsonRequestBehavior.AllowGet);
        //}
        /// <summary>
        /// 添加手术申请
        /// </summary>
        /// <returns></returns>
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public int Add(Arrangeoperation arrangeoperation)
        {
            return iarrangeoperationServices.Add(arrangeoperation);
        }
        /// <summary>
        /// 删除手术申请
        /// </summary>
        /// <returns></returns>
        public ActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public int Delete(int Id)
        {
            return iarrangeoperationServices.Delete(Id);
            //return Json(SpecialtyServices.GetSpecialties(Convert.ToInt32(DepartmentID)), JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 修改手术申请
        /// </summary>
        /// <returns></returns>
        public ActionResult Update()
        {
            return View();
        }
        [HttpPost]
        public int Update(List<Arrangeoperation> operations,int opSId, int opEId)
        {
            if (opSId != 0&& opSId!=opEId)//防止换台次时，没点击或随意点击了手术间就进入此处
            {
                List<Arrangeoperation> operationToScro = operations.Where(m => m.OperationID == opSId).OrderBy(m => m.Were).ToList();
                if (operationToScro.Count!=0)
                {
                    for (int i = 0; i < operationToScro.Count; i++)
                    {
                        operationToScro[i].Were = i + 1;
                    }
                }
            }
            return iarrangeoperationServices.Update(operations);
        }
        /// <summary>
        /// 手术室改变后，确定台次
        /// </summary>
        /// <param name="operationId"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult OpChangeReWere(int operationId,string time)
        {
            var result = iarrangeoperationServices.Show().Where(m => m.OperationID == operationId&&(m.OpeTime-DateTime.Parse(time)).Days==1).ToList();
            if (result.Count != 0)
            {
                int i= result.OrderByDescending(m => m.Were).FirstOrDefault().Were+1;
                return Json(i);
            }
            else
            {
                return Json(1);
            }
        }

        /// <summary>
        /// 获取id
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        [HttpGet]
        // GET: Users
        public JsonResult Get(string Id)
        {
            //return idepartmentServices.GetDepartments();
            return Json(iarrangeoperationServices.Get(Convert.ToInt32(Id)), JsonRequestBehavior.AllowGet);

        }
        /// <summary>
        /// 科室显示
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        // GET: Users
        public JsonResult GetDepartments()
        {
            return Json(idepartmentServices.GetDepartments(), JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 手术间
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        // GET: Users
        public JsonResult ShowOperation()
        {
            return Json(ioperation.ShowOperation(), JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult Show()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Shows(string opTime)
        {
            //var list = iarrangeoperationServices.Show().Where(m => m.OpeTime == DateTime.Parse(opTime)).ToList();
            var list = iarrangeoperationServices.Show().Where(m => (m.OpeTime - DateTime.Parse(opTime)).Days==1).ToList();
            if (list.Count!=0)
            {              
                return Json(list);
            }
            else
            {
                return Json("");
            }
        }
    }
}

HospitalManage/HospitalManage/Views/Arrangeoperation/Add.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
    <script src="~/Scripts/axios.js"></script>
    <script src="~/Scripts/vue.js"></script>
    <link href="~/css/pag.css" rel="stylesheet" media="all" />
    <link href="~/css/css.css" rel="stylesheet" media="all" />
    <link href="~/css/x-admin.css" rel="stylesheet" media="all" />
</head>
<body style="background-color:#ffffff">
    <div id="app" class="x-body">
        <table class="tablelist">
            <tr>
                <td>手术间</td>
                <td>
                    <select id="Select1" v-model="OperationNames">
                        <option value="请选择">--请选择--</option>
                        <option v-for="item in OperationList" v-bind:value="item.Id">
                            {{item.OperationName}}
                        </option>
                    </select>

                </td>
            </tr>
            <tr>
                <td>病区</td>
                <td>
                    <select id="Select1" v-model="DepartmentName">
                        <option value="请选择">--请选择--</option>
                        <option v-for="item in DepartmentList" v-bind:value="item.Id">
                            {{item.DepartmentName}}
                        </option>
                    </select>

                </td>
            </tr>
            <tr>
                <td>手术名称</td>
                <td>
                    <input id="Text1" type="text" v-model="OperationName" />
                </td>
            </tr>
            <tr>
                <td>主刀医生</td>
                <td>
                    <input id="Text1" type="text" v-model="OperatorDoctor" />
                </td>
            </tr>
            <tr>
                <td>器械</td>
                <td>
                    <input id="Text1" type="text" v-model="Instrument" />
                </td>
            </tr>
            <tr>
                <td>巡回</td>
                <td>
                    <input id="Text1" type="text" v-model="Tour" />
                </td>
            </tr>
            <tr>
                <td>麻醉</td>
                <td>
                    <input id="Text1" type="text" v-model="Anesthetist" />
                </td>
            </tr>
            <tr>
                <td>患者姓名</td>
                <td>
                    <input id="Text1" type="text" v-model="PatientName" />
                </td>
            </tr>
            <tr>
                <td>年龄</td>
                <td>
                    <input id="Text1" type="text" v-model="PatientAge" />
                </td>
            </tr>
            <tr>
                <td>性别</td>
                <td>
                    <input id="Text1" type="text" v-model="PatientSex" />
                </td>
            </tr>
            <tr>
                <td>
                    <a href="#" v-on:click="Add(OperationNames, DepartmentName, OperationName, OperatorDoctor, Instrument, Tour, Anesthetist, PatientName, PatientAge, PatientSex)"><span><img src="~/images/t01.png" /></span>保存</a>
                </td>
                <td>
                    <a href="#" onclick="location.href='/Arrangeoperation/Show'"><span><img src="~/images/t06.png" /></span>显示</a>
                </td>
            </tr>
        </table>

    </div>
    <script src="~/js/x-layui.js" charset="utf-8"></script>
    <script src="~/lib/layui/layui.js" charset="utf-8"></script>
    <script src="~/js/jquery2.js" charset="utf-8"></script>
    <script src="~/js/js.js" charset="utf-8"></script>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script>
        /*添加*/
        function new_add(title, url, w, h) {
            x_admin_show(title, url, w, h);
        }
        $('.tablelist tbody tr:odd').addClass('odd');
        // 编辑
        function data_management_look(title, url, id, w, h) {
            x_admin_show(title, url, w, h);
        }

    </script>
    <script>
        var vm = new Vue({
            el: "#app",
            data: {
                //病区
                DepartmentList: [],
                DepartmentName: "请选择",
                //手术间
                OperationList: [],
                OperationNames: "请选择",
                OperationName:"",
                OperatorDoctor:"",
                Instrument:"",
                Tour:"",
                Anesthetist:"",
                PatientName:"",
                PatientAge:"",
                PatientSex: "",
            },
            mounted() {
                this.getDepartmentList();
                this.getOperationList();
            },
            methods: {
                Add: function (OperationNames, DepartmentName, OperationName, OperatorDoctor, Instrument, Tour, Anesthetist, PatientName, PatientAge, PatientSex) {
                    axios.post('@Url.Action("Add", "Arrangeoperation")', { arrangeoperation: { OperationID: OperationNames, DepartmentID: DepartmentName, OperationName: OperationName, OperatorDoctor: OperatorDoctor, Instrument: Instrument, Tour: Tour, Anesthetist: Anesthetist, PatientName: PatientName, PatientAge: PatientAge, PatientSex: PatientSex} }).then(
                        (response) => {
                            if (response.data > 0) {
                                alert("保存成功")
                            }
                            else {
                                alert("已有该条申请")
                            }
                        },
                        (response) => {
                            alert(response.status);
                        }
                    ).catch(function (response) {
                        alert(response);
                    });
                },
                         ///获取科室的下拉菜单
                getDepartmentList: function () {
                    axios.get('@Url.Action("GetDepartments", "Arrangeoperation")').then(
                        (response) => {
                            console.log(response)
                            this.DepartmentList = response.data;
                        },
                        (response) => {
                            alert(response.status);
                        }
                    ).catch(function (response) {
                        alert(response);
                    });
                },
                         ///获取手术间的下拉菜单
                getOperationList: function () {
                    axios.get('@Url.Action("ShowOperation", "Arrangeoperation")').then(
                        (response) => {
                            console.log(response)
                            this.OperationList = response.data;
                        },
                        (response) => {
                            alert(response.status);
                        }
                    ).catch(function (response) {
                        alert(response);
                    });
                },
            }
        })

    </script>
</body>
</html>

HospitalManage/HospitalManage/Views/Arrangeoperation/Indexs.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Indexs</title>
    <script src="~/Scripts/axios.js"></script>
    <script src="~/Scripts/vue.js"></script>
</head>
<body>
    <div id="app"> 
        <table>
            <tr>
                <th>手术间</th>
                <th>台次</th>
                <th>病区</th>
                <th>手术名称</th>
                <th>主刀医生</th>
                <th>器械</th>
                <th>巡回</th>
                <th>麻醉师</th>
                <th>患者姓名</th>
                <th>年龄</th>
                <th>性别</th>
            </tr>
            <tr v-for="(contact,key,index) in OperationList">
                <td>{{contact.OperationNames}}</td> 
                <td>@*{{index+1}}*@</td>
                <td>{{contact.DepartmentName}}</td>
                <td>{{contact.OperationName}}</td>
                <td>{{contact.OperatorDoctor}}</td>
                <td>{{contact.Instrument}}</td>
                <td>{{contact.Tour}}</td>
                <td>{{contact.Anesthetist}}</td>
                <td>{{contact.PatientName}}</td>
                <td>{{contact.PatientAge}}</td>
                <td>{{contact.PatientSex}}</td>
            </tr>
        </table>
    </div>
    <script>
        var vm = new Vue({
            el: "#app",
            data: {
                OperationList: [],

            },
            mounted() {
                this.GetOperation();
            },
            methods: {
                GetOperation: function () {
                    axios.get('@Url.Action("Indexs", "Arrangeoperation")').then(
                            (response) => {
                                console.log(response)
                                this.OperationList = response.data;
                            },
                            (response) => {
                                alert(response.status);
                            }
                        ).catch(function (response) {
                            alert(response);
                        });
                },
            }
        })
    </script>
</body>
</html>